version: "3"
services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    depends_on:
      - redis
    command: conda run -n nlp_api --no-capture-output make ENV=${ENV} broker
  redis:
    image: redis
    ports:
      - 6379:6379